# Generated by Django 4.0.2 on 2022-03-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=30)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
